apiVersion: backstage.io/v1alpha1
kind: API
metadata: { name: poc-secrets-api, description: "reads private deploy-secrets.yaml cross-repo" }
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $openapi: ./openapi-secrets.yaml
